services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: melhorgestao_app
    restart: always
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'
      - 'traefik.http.routers.melhorgestao.rule=HostRegexp(`{catchall:.*}`)'
      - 'traefik.http.routers.melhorgestao.entrypoints=hidden'
      - 'traefik.http.services.melhorgestao.loadbalancer.server.port=80'
    networks:
      - proxy

networks:
  proxy:
    external: true
